repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        exclude: |
            (?x)^(
                versioneer\.py|
                theano/_version\.py|
                doc/.*|
                bin/.*
            )$
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: |
            (?x)^(
                versioneer\.py|
                theano/_version\.py|
                doc/.*|
                bin/.*
            )$
